### ISSUE TITLE
Update example include path

### ISSUE THREAD

**Issue by monkbroc** [esimkowitz/Particle-Grove-OLED#1]
The examples still use `#include <Grove_OLED_128x64/Grove_OLED_128x64.h>`. Could you please update them to `#include "Grove_OLED_128x64.h"`?

**Comment by monkbroc** [comment]
The same thing applies to https://github.com/esimkowitz/Particle-Adafruit-MCP23008 but that repo has issues disabled.

Thanks for porting those libraries and taking the time to update them to v2 format!

**Comment by esimkowitz** [comment]
Fixed in both, thanks!

**Comment by monkbroc** [comment]
Awesome, thanks!
