### ISSUE TITLE
Inappropriate use of the arduino GitHub topic

### ISSUE THREAD

**Issue by per1234** [esimkowitz/Particle-Grove-OLED#2]
The code in this repository is not compatible with the Arduino IDE or Arduino boards so it's not appropriate to use the `arduino` GitHub topic.

The topic can be removed by clicking the "Manage topics" link near the top of the repository's home page and then clicking the **X** to the right of `arduino`.

**Comment by esimkowitz** [comment]
I got your issue on my other repos and my response is the same

**Comment by esimkowitz** [comment]
I’m open to being convinced though
